### ISSUE TITLE
software installation

### ISSUE THREAD

**Issue by lokeshkamalay** [devopssq/bashscripts#6]

**Comment by srijana1993** [comment]
#!/bin/sh
echo "Number of arguments passed: $#"
echo "Installing the $1 software"
sudo yum -y install $1
if [[ $? -eq 0 ]]; then
	echo "The Software is installed successfully!"
else
	echo "Failed to install $1"
fi

**Comment by lokeshkamalay** [comment]
@srijana1993 dude you just copied my code.... Write new one that verified the no of arguments ...and fail if the args are not equals to 1
